### Import Data & Inspect Structure

In [ ]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [ ]:
# Checking how the data is encoded to properly read it in the next step
import chardet

with open("../../data/GamingStudy_data.csv", "rb") as f:
    print(chardet.detect(f.read(10000)))

{'encoding': 'ISO-8859-1', 'confidence': 0.03321167337449891, 'language': 'en', 'mime_type': 'text/plain'}

In [61]:
df = pd.read_csv('../data/GamingStudy_data.csv', encoding="ISO-8859-1")
df.head(3)

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,SWL2,SWL3,SWL4,SWL5,Game,Platform,Hours,earnings,whyplay,League,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 55 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S. No.           13464 non-null  int64
 1   Timestamp        13464 non-null  float64
 2   GAD1             13464 non-null  int64
 3   GAD2             13464 non-null  int64
 4   GAD3             13464 non-null  int64
 5   GAD4             13464 non-null  int64
 6   GAD5             13464 non-null  int64
 7   GAD6             13464 non-null  int64
 8   GAD7             13464 non-null  int64
 9   GADE             12815 non-null  str
 10  SWL1             13464 non-null  int64
 11  SWL2             13464 non-null  int64
 12  SWL3             13464 non-null  int64
 13  SWL4             13464 non-null  int64
 14  SWL5             13464 non-null  int64
 15  Game             13464 non-null  str
 16  Platform         13464 non-null  str
 17  Hours            13434 non-null  float64
 18  earnings         13464 non-null  str
 19  whyplay          13464 non-null  str
 20  League           11612 non-null  str
 21  highestleague    0 non-null      float64
 22  streams          13364 non-null  float64
 23  SPIN1            13340 non-null  float64
 24  SPIN2            13310 non-null  float64
 25  SPIN3            13324 non-null  float64
 26  SPIN4            13305 non-null  float64
 27  SPIN5            13298 non-null  float64
 28  SPIN6            13308 non-null  float64
 29  SPIN7            13326 non-null  float64
 30  SPIN8            13320 non-null  float64
 31  SPIN9            13306 non-null  float64
 32  SPIN10           13304 non-null  float64
 33  SPIN11           13277 non-null  float64
 34  SPIN12           13296 non-null  float64
 35  SPIN13           13277 non-null  float64
 36  SPIN14           13308 non-null  float64
 37  SPIN15           13317 non-null  float64
 38  SPIN16           13317 non-null  float64
 39  SPIN17           13289 non-null  float64
 40  Narcissism       13441 non-null  float64
 41  Gender           13464 non-null  str
 42  Age              13464 non-null  int64
 43  Work             13426 non-null  str
 44  Degree           11887 non-null  str
 45  Birthplace       13464 non-null  str
 46  Residence        13464 non-null  str
 47  Reference        13449 non-null  str
 48  Playstyle        13464 non-null  str
 49  accept           13050 non-null  str
 50  GAD_T            13464 non-null  int64
 51  SWL_T            13464 non-null  int64
 52  SPIN_T           12814 non-null  float64
 53  Residence_ISO3   13354 non-null  str
 54  Birthplace_ISO3  13343 non-null  str
dtypes: float64(23), int64(16), str(16)
memory usage: 5.6 MB

In [63]:
df.shape

(13464, 55)

### Explore individual columns
- `.value_counts()` for categorical variables
- `.describe()` for numerical columns
- `.loc` to compare similar columns

In [64]:
# .value_counts() for categorical variables

# ['Game', 'Platform', 'earnings', 'whyplay', 'League', 'Gender' 'Work', 'Degree', 'Birthplace', 'Residence', 'Reference', 'Playstyle']
df.value_counts('Platform')

Platform
PC                         13219
Console (PS, Xbox, ...)      222
Smartphone / Tablet           23
Name: count, dtype: int64

In [65]:
# .describe() for numerical columns

# df.describe()

In [66]:
# Compare similar columns

# df.loc[0:50, ['Residence','Residence_ISO3']]
# df.loc[0:50, ['Birthplace','Birthplace_ISO3']]

### Rename columns
- Give more context as I work with the data. See issue_log for more information

In [67]:
clean_df = df.rename(columns={
'GAD1' : 'GAD1_Feeling_nervous',
'GAD2' : 'GAD2_Cant_stop_worrying',
'GAD3' : 'GAD3_Worrying_too_much',
'GAD4' : 'GAD4_Trouble_relaxing',
'GAD5' : 'GAD5_Restless',
'GAD6' : 'GAD6_Easily_annoyed',
'GAD7' : 'GAD7_Feeling_afraid',
'GADE' : 'GADE_Difficulty_in_life',
'SWL1' : 'SWL1_Ideal_life',
'SWL2' : 'SWL2_Excellent_conditions',
'SWL3' : 'SWL3_Satisfied_with_life',
'SWL4' : 'SWL4_Met_wants',
'SWL5' : 'SWL5_Change_nothing',
'earnings' : 'Earnings',
'whyplay' : 'Why_play',
'highestleague' : 'Highest_league',
'streams' : 'Non_game_hours',
'SPIN1' : 'SPIN1_Fear_authority',
'SPIN2' : 'SPIN2_Distress_blushing',
'SPIN3' : 'SPIN3_Fear_social_events',
'SPIN4' : 'SPIN4_Avoid_strangers',
'SPIN5' : 'SPIN5_Fear_criticism',
'SPIN6' : 'SPIN6_Avoid_embarrassment',
'SPIN7' : 'SPIN7_Distress_sweating',
'SPIN8' : 'SPIN8_Avoid_parties',
'SPIN9' : 'SPIN9_Avoid_attention',
'SPIN10' : 'SPIN10_Fear_talking_strangers',
'SPIN11' : 'SPIN11_Avoid_giving_speeches',
'SPIN12' : 'SPIN12_Avoid_criticism',
'SPIN13' : 'SPIN13_Distress_heart',
'SPIN14' : 'SPIN14_Fear_observation',
'SPIN15' : 'SPIN15_Fear_embarrassment',
'SPIN16' : 'SPIN16_Avoid_authority',
'SPIN17' : 'SPIN17_Distress_trembling',
'accept' : 'Accept',
'Playstyle' : 'Play_style',
'GAD_T' : 'GAD_Total',
'SWL_T' : 'SWL_Total',
'SPIN_T' : 'SPIN_Total'
})
# clean_df.head()

In [68]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 55 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   S. No.                         13464 non-null  int64
 1   Timestamp                      13464 non-null  float64
 2   GAD1_Feeling_nervous           13464 non-null  int64
 3   GAD2_Cant_stop_worrying        13464 non-null  int64
 4   GAD3_Worrying_too_much         13464 non-null  int64
 5   GAD4_Trouble_relaxing          13464 non-null  int64
 6   GAD5_Restless                  13464 non-null  int64
 7   GAD6_Easily_annoyed            13464 non-null  int64
 8   GAD7_Feeling_afraid            13464 non-null  int64
 9   GADE_Difficulty_in_life        12815 non-null  str
 10  SWL1_Ideal_life                13464 non-null  int64
 11  SWL2_Excellent_conditions      13464 non-null  int64
 12  SWL3_Satisfied_with_life       13464 non-null  int64
 13  SWL4_Met_wants                 13464 non-null  int64
 14  SWL5_Change_nothing            13464 non-null  int64
 15  Game                           13464 non-null  str
 16  Platform                       13464 non-null  str
 17  Hours                          13434 non-null  float64
 18  Earnings                       13464 non-null  str
 19  Why_play                       13464 non-null  str
 20  League                         11612 non-null  str
 21  Highest_league                 0 non-null      float64
 22  Non_game_hours                 13364 non-null  float64
 23  SPIN1_Fear_authority           13340 non-null  float64
 24  SPIN2_Distress_blushing        13310 non-null  float64
 25  SPIN3_Fear_social_events       13324 non-null  float64
 26  SPIN4_Avoid_strangers          13305 non-null  float64
 27  SPIN5_Fear_criticism           13298 non-null  float64
 28  SPIN6_Avoid_embarrassment      13308 non-null  float64
 29  SPIN7_Distress_sweating        13326 non-null  float64
 30  SPIN8_Avoid_parties            13320 non-null  float64
 31  SPIN9_Avoid_attention          13306 non-null  float64
 32  SPIN10_Fear_talking_strangers  13304 non-null  float64
 33  SPIN11_Avoid_giving_speeches   13277 non-null  float64
 34  SPIN12_Avoid_criticism         13296 non-null  float64
 35  SPIN13_Distress_heart          13277 non-null  float64
 36  SPIN14_Fear_observation        13308 non-null  float64
 37  SPIN15_Fear_embarrassment      13317 non-null  float64
 38  SPIN16_Avoid_authority         13317 non-null  float64
 39  SPIN17_Distress_trembling      13289 non-null  float64
 40  Narcissism                     13441 non-null  float64
 41  Gender                         13464 non-null  str
 42  Age                            13464 non-null  int64
 43  Work                           13426 non-null  str
 44  Degree                         11887 non-null  str
 45  Birthplace                     13464 non-null  str
 46  Residence                      13464 non-null  str
 47  Reference                      13449 non-null  str
 48  Play_style                     13464 non-null  str
 49  Accept                         13050 non-null  str
 50  GAD_Total                      13464 non-null  int64
 51  SWL_Total                      13464 non-null  int64
 52  SPIN_Total                     12814 non-null  float64
 53  Residence_ISO3                 13354 non-null  str
 54  Birthplace_ISO3                13343 non-null  str
dtypes: float64(23), int64(16), str(16)
memory usage: 5.6 MB

In [69]:
clean_df.value_counts('Hours')

Hours
20.0     2293
10.0     1375
30.0     1186
15.0     1115
25.0      831
         ...
420.0       1
110.0       1
112.0       1
96.0        1
150.0       1
Name: count, Length: 84, dtype: int64

Dropped unnecessary columns in new dataframe

In [70]:
clean_df.drop('Highest_league', axis=1, inplace=True)
clean_df.head()

,S. No.,Timestamp,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20.0,I play for fun,improving,NaN,5.0,2.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,2.0,Male,28,Employed,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,having fun,NaN,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,Male,19,Employed,High school diploma (or equivalent),USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA

Reset datatype to int (see issue_log for more info)

In [71]:
# clean_df['SPIN1_Fear_authority'] = clean_df['SPIN1_Fear_authority'].astype(int)

### Investigate NaN values in rows

In [72]:
# clean_df.isna().sum()

In [73]:
# clean_df.loc[:,['SPIN1_Fear_authority','SPIN2_Distress_blushing','SPIN3_Fear_social_events','SPIN4_Avoid_strangers']].isnull()

In [74]:
# clean_df[clean_df[['SPIN1_Fear_authority', 'SPIN2_Distress_blushing','SPIN3_Fear_social_events','SPIN4_Avoid_strangers','SPIN5_Fear_criticism','SPIN6_Avoid_embarrassment','SPIN7_Distress_sweating','SPIN8_Avoid_parties','SPIN9_Avoid_attention','SPIN10_Fear_talking_strangers','SPIN11_Avoid_giving_speeches','SPIN12_Avoid_criticism','SPIN13_Distress_heart','SPIN14_Fear_observation','SPIN15_Fear_embarrassment','SPIN16_Avoid_authority','SPIN17_Distress_trembling']].isna().any(axis=1)]

In [75]:
clean_df[clean_df['SPIN_Total'].isna()]

,S. No.,Timestamp,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3
7,8,42052.15930,0,0,0,0,0,0,0,NaN,3,6,4,3,7,Other,"Console (PS, Xbox, ...)",25.0,I play for fun,having fun,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,5.0,Female,23,Employed,Bachelor (or equivalent),USA,Japan,Reddit,Singleplayer,Accept,0,23,NaN,JPN,USA
36,37,42052.72080,1,1,0,0,0,1,1,Somewhat difficult,5,5,5,3,6,Other,PC,18.0,I play for fun,having fun,NaN,3.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,NaN,2.0,1.0,1.0,0.0,1.0,1.0,Female,22,Student at college / university,High school diploma (or equivalent),Greece,Greece,Reddit,Multiplayer - online - with real life friends,Accept,4,24,NaN,GRC,GRC
55,57,42052.89404,0,0,0,0,0,0,0,Not difficult at all,6,7,6,5,2,Counter Strike,PC,30.0,I play for fun,improving,Silver 2,2.0,1.0,0.0,3.0,2.0,3.0,NaN,0.0,4.0,3.0,1.0,3.0,2.0,0.0,1.0,0.0,0.0,0.0,2.0,Male,18,Student at school,NaN,Bulgaria,UK,Reddit,Multiplayer - online - with real life friends,Accept,0,26,NaN,GBR,BGR
67,70,42053.07287,0,0,0,0,0,0,0,NaN,6,7,7,7,4,Other,PC,40.0,I play for fun,having fun,bad,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Male,19,Student at school,High school diploma (or equivalent),USA,USA,Reddit,Multiplayer - online - with real life friends,Accept,0,31,NaN,USA,USA
89,92,42053.82787,3,3,3,3,3,1,2,Somewhat difficult,5,7,5,5,1,Other,Smartphone / Tablet,9.0,I play for fun,having fun,NaN,1.0,2.0,4.0,1.0,2.0,NaN,1.0,0.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,2.0,Male,19,Student at college / university,High school diploma (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,18,23,NaN,USA,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13368,14154,42055.66921,0,0,0,0,0,2,0,Not difficult at all,7,5,7,7,6,League of Legends,PC,20.0,I play mostly for fun but earn a little on the...,having fun,g1,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Male,21,Employed,Bachelor (or equivalent),UK,UK,Reddit,Multiplayer - online - with real life friends,Accept,2,32,NaN,GBR,GBR
13419,14205,42055.79394,3,3,2,2,2,1,1,Somewhat difficult,2,2,2,2,1,League of Legends,PC,15.0,I play for fun,having fun,Gold 1,12.0,1.0,1.0,2.0,3.0,NaN,3.0,0.0,0.0,2.0,3.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,3.0,Male,18,Student at school,High school diploma (or equivalent),Sweden,Sweden,Reddit,Multiplayer - online - with real life friends,Accept,14,9,NaN,SWE,SWE
13435,14221,42056.00784,1,1,2,3,0,1,0,Not difficult at all,5,5,4,3,3,League of Legends,PC,8.0,I play for fun,having fun,Gold V,5.0,1.0,0.0,0.0,1.0,2.0,1.0,4.0,0.0,3.0,2.0,NaN,3.0,1.0,3.0,3.0,0.0,4.0,1.0,Female,21,Student at college / university,High school diploma (or equivalent),USA,USA,Reddit,Multiplayer - online - with real life friends,Accept,8,20,NaN,USA,USA
13442,14228,42056.29025,0,0,0,0,0,1,0,Somewhat difficult,3,5,6,5,3,Starcraft 2,PC,24.0,Strive to be Pro,improving,Gold,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,0.0,1.0,1.0,Male,18,Student at school,High school diploma (or equivalent),USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,1,22,NaN,USA,USA
13454,14240,42056.97403,1,1,1,1,1,1,0,Somewhat difficult,2,3,3,2,2,League of Legends,"Console (PS, Xbox, ...)",40.0,I play for fun,winning,Plat 5,20.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,2.0,NaN,2.0,0.0,3.0,3.0,2.0,2.0,2.0,Male,24,Employed,High school diploma (or equivalent),USA,USA,Reddit,Multiplayer - online - with real life friends,Accept,6,12,NaN,USA,USA

Remove <5% of data where SPIN_Total = NaN

In [76]:
clean_df = clean_df.dropna(subset=['SPIN_Total'])
clean_df.shape

(12814, 54)

In [77]:
# clean_df.isna().sum()

In [78]:
# clean_df[clean_df['GADE_Difficulty_in_life'].isna()]

Remove <5% of data where GADE_Difficulty_in_life = NaN

In [79]:
clean_df = clean_df.dropna(subset=['GADE_Difficulty_in_life'])
clean_df.shape

(12188, 54)

In [80]:
# clean_df.isna().sum()

In [81]:
# clean_df[clean_df['Hours'].isna()]

Remove 26 rows where Hours is NaN

In [82]:
clean_df = clean_df.dropna(subset=['Hours'])
clean_df.shape

(12162, 54)

### Convert floats to ints

In [83]:
clean_df['SPIN1_Fear_authority'] = clean_df['SPIN1_Fear_authority'].astype(int)
clean_df.info()

<class 'pandas.DataFrame'>
Index: 12162 entries, 0 to 13463
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   S. No.                         12162 non-null  int64
 1   Timestamp                      12162 non-null  float64
 2   GAD1_Feeling_nervous           12162 non-null  int64
 3   GAD2_Cant_stop_worrying        12162 non-null  int64
 4   GAD3_Worrying_too_much         12162 non-null  int64
 5   GAD4_Trouble_relaxing          12162 non-null  int64
 6   GAD5_Restless                  12162 non-null  int64
 7   GAD6_Easily_annoyed            12162 non-null  int64
 8   GAD7_Feeling_afraid            12162 non-null  int64
 9   GADE_Difficulty_in_life        12162 non-null  str
 10  SWL1_Ideal_life                12162 non-null  int64
 11  SWL2_Excellent_conditions      12162 non-null  int64
 12  SWL3_Satisfied_with_life       12162 non-null  int64
 13  SWL4_Met_wants                 12162 non-null  int64
 14  SWL5_Change_nothing            12162 non-null  int64
 15  Game                           12162 non-null  str
 16  Platform                       12162 non-null  str
 17  Hours                          12162 non-null  float64
 18  Earnings                       12162 non-null  str
 19  Why_play                       12162 non-null  str
 20  League                         10472 non-null  str
 21  Non_game_hours                 12081 non-null  float64
 22  SPIN1_Fear_authority           12162 non-null  int64
 23  SPIN2_Distress_blushing        12162 non-null  float64
 24  SPIN3_Fear_social_events       12162 non-null  float64
 25  SPIN4_Avoid_strangers          12162 non-null  float64
 26  SPIN5_Fear_criticism           12162 non-null  float64
 27  SPIN6_Avoid_embarrassment      12162 non-null  float64
 28  SPIN7_Distress_sweating        12162 non-null  float64
 29  SPIN8_Avoid_parties            12162 non-null  float64
 30  SPIN9_Avoid_attention          12162 non-null  float64
 31  SPIN10_Fear_talking_strangers  12162 non-null  float64
 32  SPIN11_Avoid_giving_speeches   12162 non-null  float64
 33  SPIN12_Avoid_criticism         12162 non-null  float64
 34  SPIN13_Distress_heart          12162 non-null  float64
 35  SPIN14_Fear_observation        12162 non-null  float64
 36  SPIN15_Fear_embarrassment      12162 non-null  float64
 37  SPIN16_Avoid_authority         12162 non-null  float64
 38  SPIN17_Distress_trembling      12162 non-null  float64
 39  Narcissism                     12152 non-null  float64
 40  Gender                         12162 non-null  str
 41  Age                            12162 non-null  int64
 42  Work                           12132 non-null  str
 43  Degree                         10750 non-null  str
 44  Birthplace                     12162 non-null  str
 45  Residence                      12162 non-null  str
 46  Reference                      12151 non-null  str
 47  Play_style                     12162 non-null  str
 48  Accept                         11799 non-null  str
 49  GAD_Total                      12162 non-null  int64
 50  SWL_Total                      12162 non-null  int64
 51  SPIN_Total                     12162 non-null  float64
 52  Residence_ISO3                 12066 non-null  str
 53  Birthplace_ISO3                12059 non-null  str
dtypes: float64(21), int64(17), str(16)
memory usage: 5.1 MB

In [84]:
convert_cols = ['Hours','SPIN2_Distress_blushing','SPIN3_Fear_social_events','SPIN4_Avoid_strangers','SPIN5_Fear_criticism','SPIN6_Avoid_embarrassment','SPIN7_Distress_sweating','SPIN8_Avoid_parties','SPIN9_Avoid_attention','SPIN10_Fear_talking_strangers','SPIN11_Avoid_giving_speeches','SPIN12_Avoid_criticism','SPIN13_Distress_heart','SPIN14_Fear_observation','SPIN15_Fear_embarrassment','SPIN16_Avoid_authority','SPIN17_Distress_trembling', 'SPIN_Total']
clean_df[convert_cols] = clean_df[convert_cols].astype(int)
clean_df.info()

<class 'pandas.DataFrame'>
Index: 12162 entries, 0 to 13463
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   S. No.                         12162 non-null  int64
 1   Timestamp                      12162 non-null  float64
 2   GAD1_Feeling_nervous           12162 non-null  int64
 3   GAD2_Cant_stop_worrying        12162 non-null  int64
 4   GAD3_Worrying_too_much         12162 non-null  int64
 5   GAD4_Trouble_relaxing          12162 non-null  int64
 6   GAD5_Restless                  12162 non-null  int64
 7   GAD6_Easily_annoyed            12162 non-null  int64
 8   GAD7_Feeling_afraid            12162 non-null  int64
 9   GADE_Difficulty_in_life        12162 non-null  str
 10  SWL1_Ideal_life                12162 non-null  int64
 11  SWL2_Excellent_conditions      12162 non-null  int64
 12  SWL3_Satisfied_with_life       12162 non-null  int64
 13  SWL4_Met_wants                 12162 non-null  int64
 14  SWL5_Change_nothing            12162 non-null  int64
 15  Game                           12162 non-null  str
 16  Platform                       12162 non-null  str
 17  Hours                          12162 non-null  int64
 18  Earnings                       12162 non-null  str
 19  Why_play                       12162 non-null  str
 20  League                         10472 non-null  str
 21  Non_game_hours                 12081 non-null  float64
 22  SPIN1_Fear_authority           12162 non-null  int64
 23  SPIN2_Distress_blushing        12162 non-null  int64
 24  SPIN3_Fear_social_events       12162 non-null  int64
 25  SPIN4_Avoid_strangers          12162 non-null  int64
 26  SPIN5_Fear_criticism           12162 non-null  int64
 27  SPIN6_Avoid_embarrassment      12162 non-null  int64
 28  SPIN7_Distress_sweating        12162 non-null  int64
 29  SPIN8_Avoid_parties            12162 non-null  int64
 30  SPIN9_Avoid_attention          12162 non-null  int64
 31  SPIN10_Fear_talking_strangers  12162 non-null  int64
 32  SPIN11_Avoid_giving_speeches   12162 non-null  int64
 33  SPIN12_Avoid_criticism         12162 non-null  int64
 34  SPIN13_Distress_heart          12162 non-null  int64
 35  SPIN14_Fear_observation        12162 non-null  int64
 36  SPIN15_Fear_embarrassment      12162 non-null  int64
 37  SPIN16_Avoid_authority         12162 non-null  int64
 38  SPIN17_Distress_trembling      12162 non-null  int64
 39  Narcissism                     12152 non-null  float64
 40  Gender                         12162 non-null  str
 41  Age                            12162 non-null  int64
 42  Work                           12132 non-null  str
 43  Degree                         10750 non-null  str
 44  Birthplace                     12162 non-null  str
 45  Residence                      12162 non-null  str
 46  Reference                      12151 non-null  str
 47  Play_style                     12162 non-null  str
 48  Accept                         11799 non-null  str
 49  GAD_Total                      12162 non-null  int64
 50  SWL_Total                      12162 non-null  int64
 51  SPIN_Total                     12162 non-null  int64
 52  Residence_ISO3                 12066 non-null  str
 53  Birthplace_ISO3                12059 non-null  str
dtypes: float64(3), int64(35), str(16)
memory usage: 5.1 MB

Remove original residence & birthplace info now that they've been converted to ISO3 in other columns

In [85]:
clean_df.drop(['Birthplace', 'Residence'], axis=1, inplace=True)
clean_df.head()

,S. No.,Timestamp,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15,I play for fun,having fun,NaN,0.0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Singleplayer,Accept,1,23,5,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8,I play for fun,having fun,NaN,2.0,2,1,1,3,2,3,1,3,4,0,3,0,1,3,3,1,2,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,8,16,33,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0,I play for fun,having fun,NaN,0.0,1,0,1,2,3,4,2,1,0,1,1,3,0,2,4,4,2,4.0,Female,32,Employed,Bachelor (or equivalent),Reddit,Singleplayer,Accept,8,17,31,DEU,DEU
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20,I play for fun,improving,NaN,5.0,2,0,0,1,3,0,0,0,0,0,1,3,0,0,1,0,0,2.0,Male,28,Employed,Bachelor (or equivalent),Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11,USA,USA
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20,I play for fun,having fun,NaN,1.0,2,0,0,0,1,0,0,4,2,0,1,0,0,0,0,3,0,1.0,Male,19,Employed,High school diploma (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,14,14,13,KOR,USA

### Fix the Timestamp format

In [86]:
clean_df.head()

,S. No.,Timestamp,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15,I play for fun,having fun,NaN,0.0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Singleplayer,Accept,1,23,5,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8,I play for fun,having fun,NaN,2.0,2,1,1,3,2,3,1,3,4,0,3,0,1,3,3,1,2,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,8,16,33,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0,I play for fun,having fun,NaN,0.0,1,0,1,2,3,4,2,1,0,1,1,3,0,2,4,4,2,4.0,Female,32,Employed,Bachelor (or equivalent),Reddit,Singleplayer,Accept,8,17,31,DEU,DEU
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20,I play for fun,improving,NaN,5.0,2,0,0,1,3,0,0,0,0,0,1,3,0,0,1,0,0,2.0,Male,28,Employed,Bachelor (or equivalent),Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11,USA,USA
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20,I play for fun,having fun,NaN,1.0,2,0,0,0,1,0,0,4,2,0,1,0,0,0,0,3,0,1.0,Male,19,Employed,High school diploma (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,14,14,13,KOR,USA

In [87]:
# Reference: https://stackoverflow.com/questions/38454403/convert-excel-style-date-with-pandas
# Reference: https://stackoverflow.com/questions/29310116/removing-time-from-datetime-variable-in-pandas 
clean_df['Date'] = pd.to_datetime(clean_df['Timestamp'], unit='D', origin='1899-12-30').dt.normalize()
clean_df.head()

,S. No.,Timestamp,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3,Date
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15,I play for fun,having fun,NaN,0.0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Singleplayer,Accept,1,23,5,USA,USA,2015-02-17
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8,I play for fun,having fun,NaN,2.0,2,1,1,3,2,3,1,3,4,0,3,0,1,3,3,1,2,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,8,16,33,USA,USA,2015-02-17
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0,I play for fun,having fun,NaN,0.0,1,0,1,2,3,4,2,1,0,1,1,3,0,2,4,4,2,4.0,Female,32,Employed,Bachelor (or equivalent),Reddit,Singleplayer,Accept,8,17,31,DEU,DEU,2015-02-17
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20,I play for fun,improving,NaN,5.0,2,0,0,1,3,0,0,0,0,0,1,3,0,0,1,0,0,2.0,Male,28,Employed,Bachelor (or equivalent),Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11,USA,USA,2015-02-17
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20,I play for fun,having fun,NaN,1.0,2,0,0,0,1,0,0,4,2,0,1,0,0,0,0,3,0,1.0,Male,19,Employed,High school diploma (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,14,14,13,KOR,USA,2015-02-17

In [88]:
col_to_move = clean_df.pop('Date')
clean_df.insert(2, 'Date', col_to_move)
clean_df.head()

,S. No.,Timestamp,Date,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,2015-02-17,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15,I play for fun,having fun,NaN,0.0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Singleplayer,Accept,1,23,5,USA,USA
1,2,42052.00680,2015-02-17,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8,I play for fun,having fun,NaN,2.0,2,1,1,3,2,3,1,3,4,0,3,0,1,3,3,1,2,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,8,16,33,USA,USA
2,3,42052.03860,2015-02-17,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0,I play for fun,having fun,NaN,0.0,1,0,1,2,3,4,2,1,0,1,1,3,0,2,4,4,2,4.0,Female,32,Employed,Bachelor (or equivalent),Reddit,Singleplayer,Accept,8,17,31,DEU,DEU
3,4,42052.06804,2015-02-17,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20,I play for fun,improving,NaN,5.0,2,0,0,1,3,0,0,0,0,0,1,3,0,0,1,0,0,2.0,Male,28,Employed,Bachelor (or equivalent),Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11,USA,USA
4,5,42052.08948,2015-02-17,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20,I play for fun,having fun,NaN,1.0,2,0,0,0,1,0,0,4,2,0,1,0,0,0,0,3,0,1.0,Male,19,Employed,High school diploma (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,14,14,13,KOR,USA

In [89]:
# clean_df.info()

Remove original timestamp column

In [90]:
clean_df = clean_df.drop(columns='Timestamp')
clean_df.head()

,S. No.,Date,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3
0,1,2015-02-17,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15,I play for fun,having fun,NaN,0.0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Singleplayer,Accept,1,23,5,USA,USA
1,2,2015-02-17,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8,I play for fun,having fun,NaN,2.0,2,1,1,3,2,3,1,3,4,0,3,0,1,3,3,1,2,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,8,16,33,USA,USA
2,3,2015-02-17,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0,I play for fun,having fun,NaN,0.0,1,0,1,2,3,4,2,1,0,1,1,3,0,2,4,4,2,4.0,Female,32,Employed,Bachelor (or equivalent),Reddit,Singleplayer,Accept,8,17,31,DEU,DEU
3,4,2015-02-17,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20,I play for fun,improving,NaN,5.0,2,0,0,1,3,0,0,0,0,0,1,3,0,0,1,0,0,2.0,Male,28,Employed,Bachelor (or equivalent),Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11,USA,USA
4,5,2015-02-17,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20,I play for fun,having fun,NaN,1.0,2,0,0,0,1,0,0,4,2,0,1,0,0,0,0,3,0,1.0,Male,19,Employed,High school diploma (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,14,14,13,KOR,USA

### Convert row data to ints
- GADE_Difficulty_in_life transform to int to match other data
- Need to specify what str to what int > lambda function?

In [91]:
clean_df.info()

<class 'pandas.DataFrame'>
Index: 12162 entries, 0 to 13463
Data columns (total 52 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   S. No.                         12162 non-null  int64
 1   Date                           12162 non-null  datetime64[ns]
 2   GAD1_Feeling_nervous           12162 non-null  int64
 3   GAD2_Cant_stop_worrying        12162 non-null  int64
 4   GAD3_Worrying_too_much         12162 non-null  int64
 5   GAD4_Trouble_relaxing          12162 non-null  int64
 6   GAD5_Restless                  12162 non-null  int64
 7   GAD6_Easily_annoyed            12162 non-null  int64
 8   GAD7_Feeling_afraid            12162 non-null  int64
 9   GADE_Difficulty_in_life        12162 non-null  str
 10  SWL1_Ideal_life                12162 non-null  int64
 11  SWL2_Excellent_conditions      12162 non-null  int64
 12  SWL3_Satisfied_with_life       12162 non-null  int64
 13  SWL4_Met_wants                 12162 non-null  int64
 14  SWL5_Change_nothing            12162 non-null  int64
 15  Game                           12162 non-null  str
 16  Platform                       12162 non-null  str
 17  Hours                          12162 non-null  int64
 18  Earnings                       12162 non-null  str
 19  Why_play                       12162 non-null  str
 20  League                         10472 non-null  str
 21  Non_game_hours                 12081 non-null  float64
 22  SPIN1_Fear_authority           12162 non-null  int64
 23  SPIN2_Distress_blushing        12162 non-null  int64
 24  SPIN3_Fear_social_events       12162 non-null  int64
 25  SPIN4_Avoid_strangers          12162 non-null  int64
 26  SPIN5_Fear_criticism           12162 non-null  int64
 27  SPIN6_Avoid_embarrassment      12162 non-null  int64
 28  SPIN7_Distress_sweating        12162 non-null  int64
 29  SPIN8_Avoid_parties            12162 non-null  int64
 30  SPIN9_Avoid_attention          12162 non-null  int64
 31  SPIN10_Fear_talking_strangers  12162 non-null  int64
 32  SPIN11_Avoid_giving_speeches   12162 non-null  int64
 33  SPIN12_Avoid_criticism         12162 non-null  int64
 34  SPIN13_Distress_heart          12162 non-null  int64
 35  SPIN14_Fear_observation        12162 non-null  int64
 36  SPIN15_Fear_embarrassment      12162 non-null  int64
 37  SPIN16_Avoid_authority         12162 non-null  int64
 38  SPIN17_Distress_trembling      12162 non-null  int64
 39  Narcissism                     12152 non-null  float64
 40  Gender                         12162 non-null  str
 41  Age                            12162 non-null  int64
 42  Work                           12132 non-null  str
 43  Degree                         10750 non-null  str
 44  Reference                      12151 non-null  str
 45  Play_style                     12162 non-null  str
 46  Accept                         11799 non-null  str
 47  GAD_Total                      12162 non-null  int64
 48  SWL_Total                      12162 non-null  int64
 49  SPIN_Total                     12162 non-null  int64
 50  Residence_ISO3                 12066 non-null  str
 51  Birthplace_ISO3                12059 non-null  str
dtypes: datetime64[ns](1), float64(2), int64(35), str(14)
memory usage: 4.9 MB

In [92]:
clean_df['GADE_Difficulty_in_life'].value_counts()

GADE_Difficulty_in_life
Not difficult at all    5921
Somewhat difficult      4877
Very difficult           974
Extremely difficult      390
Name: count, dtype: int64

Convert data in the GADE_Difficulty_in_life column to numbers to better reflect how the data was originally gathered and scored.

In [93]:
# Reference: https://www.geeksforgeeks.org/pandas/applying-lambda-functions-to-pandas-dataframe/
# Reference: https://stackoverflow.com/questions/44991438/lambda-including-if-elif-else

# DON'T UNCOMMENT. THIS DOESN'T DO WHAT YOU WANT IT TO. KEEPING FOR POSTERITY.

# def rename_GADE_Difficulty(x):
#     if x == 'Not difficult at all':
#         x=0
#     elif x == 'Somewhat difficult':
#         x=1
#     elif x == 'Very difficult':
#         x=2
#     else: x=3

# clean_df['GADE_Difficulty_in_life'] = clean_df['GADE_Difficulty_in_life'].apply(
#     lambda x: rename_GADE_Difficulty(x))
# clean_df['GADE_Difficulty_in_life'].value_counts()

In [94]:
# TAKE TWO!
# Reference: https://www.geeksforgeeks.org/python/python-pandas-map/

rubric_map = {
    'Not difficult at all' : 0,
    'Somewhat difficult' : 1,
    'Very difficult' : 2,
    'Extremely difficult' : 3
}

clean_df['GADE_Difficulty_in_life_num'] = clean_df['GADE_Difficulty_in_life'].map(rubric_map)
clean_df.head()

,S. No.,Date,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3,GADE_Difficulty_in_life_num
0,1,2015-02-17,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15,I play for fun,having fun,NaN,0.0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Singleplayer,Accept,1,23,5,USA,USA,0
1,2,2015-02-17,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8,I play for fun,having fun,NaN,2.0,2,1,1,3,2,3,1,3,4,0,3,0,1,3,3,1,2,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,8,16,33,USA,USA,1
2,3,2015-02-17,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0,I play for fun,having fun,NaN,0.0,1,0,1,2,3,4,2,1,0,1,1,3,0,2,4,4,2,4.0,Female,32,Employed,Bachelor (or equivalent),Reddit,Singleplayer,Accept,8,17,31,DEU,DEU,0
3,4,2015-02-17,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20,I play for fun,improving,NaN,5.0,2,0,0,1,3,0,0,0,0,0,1,3,0,0,1,0,0,2.0,Male,28,Employed,Bachelor (or equivalent),Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11,USA,USA,0
4,5,2015-02-17,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20,I play for fun,having fun,NaN,1.0,2,0,0,0,1,0,0,4,2,0,1,0,0,0,0,3,0,1.0,Male,19,Employed,High school diploma (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,14,14,13,KOR,USA,2

In [95]:
col_to_move = clean_df.pop('GADE_Difficulty_in_life_num')
clean_df.insert(9, 'GADE_Difficulty_in_life_num', col_to_move)
clean_df.head()

,S. No.,Date,GAD1_Feeling_nervous,GAD2_Cant_stop_worrying,GAD3_Worrying_too_much,GAD4_Trouble_relaxing,GAD5_Restless,GAD6_Easily_annoyed,GAD7_Feeling_afraid,GADE_Difficulty_in_life_num,GADE_Difficulty_in_life,SWL1_Ideal_life,SWL2_Excellent_conditions,SWL3_Satisfied_with_life,SWL4_Met_wants,SWL5_Change_nothing,Game,Platform,Hours,Earnings,Why_play,League,Non_game_hours,SPIN1_Fear_authority,SPIN2_Distress_blushing,SPIN3_Fear_social_events,SPIN4_Avoid_strangers,SPIN5_Fear_criticism,SPIN6_Avoid_embarrassment,SPIN7_Distress_sweating,SPIN8_Avoid_parties,SPIN9_Avoid_attention,SPIN10_Fear_talking_strangers,SPIN11_Avoid_giving_speeches,SPIN12_Avoid_criticism,SPIN13_Distress_heart,SPIN14_Fear_observation,SPIN15_Fear_embarrassment,SPIN16_Avoid_authority,SPIN17_Distress_trembling,Narcissism,Gender,Age,Work,Degree,Reference,Play_style,Accept,GAD_Total,SWL_Total,SPIN_Total,Residence_ISO3,Birthplace_ISO3
0,1,2015-02-17,0,0,0,0,1,0,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15,I play for fun,having fun,NaN,0.0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Singleplayer,Accept,1,23,5,USA,USA
1,2,2015-02-17,1,2,2,2,0,1,0,1,Somewhat difficult,3,5,2,5,1,Other,PC,8,I play for fun,having fun,NaN,2.0,2,1,1,3,2,3,1,3,4,0,3,0,1,3,3,1,2,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,8,16,33,USA,USA
2,3,2015-02-17,0,2,2,0,0,3,1,0,Not difficult at all,2,6,5,2,2,Other,PC,0,I play for fun,having fun,NaN,0.0,1,0,1,2,3,4,2,1,0,1,1,3,0,2,4,4,2,4.0,Female,32,Employed,Bachelor (or equivalent),Reddit,Singleplayer,Accept,8,17,31,DEU,DEU
3,4,2015-02-17,0,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20,I play for fun,improving,NaN,5.0,2,0,0,1,3,0,0,0,0,0,1,3,0,0,1,0,0,2.0,Male,28,Employed,Bachelor (or equivalent),Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11,USA,USA
4,5,2015-02-17,2,1,2,2,2,3,2,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20,I play for fun,having fun,NaN,1.0,2,0,0,0,1,0,0,4,2,0,1,0,0,0,0,3,0,1.0,Male,19,Employed,High school diploma (or equivalent),Reddit,Multiplayer - online - with strangers,Accept,14,14,13,KOR,USA

Ensure the new column's data is stored as int

In [96]:
clean_df['GADE_Difficulty_in_life_num'] = clean_df['GADE_Difficulty_in_life_num'].astype(int)

Confirm the mapping worked

In [97]:

clean_df['GADE_Difficulty_in_life'].value_counts()

GADE_Difficulty_in_life
Not difficult at all    5921
Somewhat difficult      4877
Very difficult           974
Extremely difficult      390
Name: count, dtype: int64

In [98]:
clean_df['GADE_Difficulty_in_life_num'].value_counts()

GADE_Difficulty_in_life_num
0    5921
1    4877
2     974
3     390
Name: count, dtype: int64

### Investigate remaining NaN rows
| Column Name        | Notes                              |
|--------------------|------------------------------------|
| League             | 1690 - replaced with 'unknown'     |
| Non-game hours     | 81 - not super important. will set to -1 and int|
| Narcissism         | 10 - dropped rows                  |
| Work               | 30 - replaced with 'Unknown'       |
| Degree             | 1412 - replaced with 'Unknown'     |
| Reference          | Non-issue; could maybe be removed  |
| Accept             | Non-issue; could remove if desired |
| Residence_ISO3     | Change to UNK (Unknown)            |
| Birthplace_ISO3    | Change to UNK (Unknown)            |

In [99]:
# clean_df.isna().sum()

Checking NaN in original data from Birthplace and Residence to see how they affect the ISO3 columns.  
Conclusion: if data is unknown: NaN

In [100]:
# df[df['Birthplace_ISO3'].isna()]

In [101]:
# clean_df[clean_df[['Birthplace_ISO3', 'Residence_ISO3']].isna().any(axis=1)]

Filled NaN in Birthplace and Residence with 'UNK' for 'unknown'

In [102]:
clean_df[['Birthplace_ISO3', 'Residence_ISO3']] = clean_df[['Birthplace_ISO3', 'Residence_ISO3']].fillna('UNK')
# clean_df[clean_df[['Birthplace_ISO3', 'Residence_ISO3']].isna().any(axis=1)]

In [103]:
# clean_df['Non_game_hours'].value_counts()
# clean_df[clean_df[['Non_game_hours']].isna().any(axis=1)]

Replace non-game hours with -1 for NaN (for any analysis of this data, ignore if <0)

In [104]:
clean_df['Non_game_hours'] = clean_df['Non_game_hours'].fillna(-1)
clean_df['Non_game_hours'] = clean_df['Non_game_hours'].astype('int')
# clean_df[clean_df[['Non_game_hours']].isna().any(axis=1)]
# clean_df.isna().sum()
# clean_df.info()

Replace NaN in 'League' with 'unknown'

In [105]:
clean_df['League'] = clean_df['League'].fillna('unknown')
# clean_df[clean_df['League'].isna()]

Evaluate and decide to remove the 10 rows of NaN in 'Narcissism' column

In [106]:
# clean_df[clean_df['Narcissism'].isna()]
# clean_df.head()
# clean_df['Narcissism'].value_counts()
# clean_df['Narcissism'].isna().sum()

clean_df = clean_df.dropna(subset=['Narcissism'])
clean_df['Narcissism'].isna().sum()

# clean_df.info()

np.int64(0)

Evaluate and decide about NaN 'Work' rows > Replace with 'Unknown'

In [107]:
# clean_df[clean_df['Work'].isna()]
# clean_df.head()
# clean_df['Work'].value_counts()
# clean_df['Work'].isna().sum()
clean_df['Work'] = clean_df['Work'].fillna('Unknown')

clean_df[clean_df['Work'].isna()]

Empty DataFrame
Columns: [S. No., Date, GAD1_Feeling_nervous, GAD2_Cant_stop_worrying, GAD3_Worrying_too_much, GAD4_Trouble_relaxing, GAD5_Restless, GAD6_Easily_annoyed, GAD7_Feeling_afraid, GADE_Difficulty_in_life_num, GADE_Difficulty_in_life, SWL1_Ideal_life, SWL2_Excellent_conditions, SWL3_Satisfied_with_life, SWL4_Met_wants, SWL5_Change_nothing, Game, Platform, Hours, Earnings, Why_play, League, Non_game_hours, SPIN1_Fear_authority, SPIN2_Distress_blushing, SPIN3_Fear_social_events, SPIN4_Avoid_strangers, SPIN5_Fear_criticism, SPIN6_Avoid_embarrassment, SPIN7_Distress_sweating, SPIN8_Avoid_parties, SPIN9_Avoid_attention, SPIN10_Fear_talking_strangers, SPIN11_Avoid_giving_speeches, SPIN12_Avoid_criticism, SPIN13_Distress_heart, SPIN14_Fear_observation, SPIN15_Fear_embarrassment, SPIN16_Avoid_authority, SPIN17_Distress_trembling, Narcissism, Gender, Age, Work, Degree, Reference, Play_style, Accept, GAD_Total, SWL_Total, SPIN_Total, Residence_ISO3, Birthplace_ISO3]
Index: []

Evaluate and decide about NaN 'Degree' rows > Replace with 'Unknown'

In [108]:
clean_df[clean_df['Degree'].isna()]
clean_df.head()
clean_df['Degree'].value_counts()
clean_df['Degree'].isna().sum()
clean_df['Degree'] = clean_df['Degree'].fillna('Unknown')

clean_df[clean_df['Degree'].isna()]

Empty DataFrame
Columns: [S. No., Date, GAD1_Feeling_nervous, GAD2_Cant_stop_worrying, GAD3_Worrying_too_much, GAD4_Trouble_relaxing, GAD5_Restless, GAD6_Easily_annoyed, GAD7_Feeling_afraid, GADE_Difficulty_in_life_num, GADE_Difficulty_in_life, SWL1_Ideal_life, SWL2_Excellent_conditions, SWL3_Satisfied_with_life, SWL4_Met_wants, SWL5_Change_nothing, Game, Platform, Hours, Earnings, Why_play, League, Non_game_hours, SPIN1_Fear_authority, SPIN2_Distress_blushing, SPIN3_Fear_social_events, SPIN4_Avoid_strangers, SPIN5_Fear_criticism, SPIN6_Avoid_embarrassment, SPIN7_Distress_sweating, SPIN8_Avoid_parties, SPIN9_Avoid_attention, SPIN10_Fear_talking_strangers, SPIN11_Avoid_giving_speeches, SPIN12_Avoid_criticism, SPIN13_Distress_heart, SPIN14_Fear_observation, SPIN15_Fear_embarrassment, SPIN16_Avoid_authority, SPIN17_Distress_trembling, Narcissism, Gender, Age, Work, Degree, Reference, Play_style, Accept, GAD_Total, SWL_Total, SPIN_Total, Residence_ISO3, Birthplace_ISO3]
Index: []

### Check for duplicate rows
No duplicate rows

In [109]:

clean_df.duplicated().sum()

np.int64(0)

### Investigate outliers in 'Hours'

There are 168 hours in a week. I will be filtering out any values that exceed this number and note the high outliers as they did not account for sleep. The same will apply to the non-game hours column.

I will also remove any rows where 'Hours' + 'Non-game-hours' > 168.

Rows removed: 7

In [110]:
sorted_hrs_df = clean_df.sort_values(by='Hours', ascending=False)
sorted_hrs_df.head(15)

clean_df = clean_df[clean_df['Hours'] <= 168]

In [111]:
# sorted_hrs_df = clean_df.sort_values(by='Hours', ascending=False)
# sorted_hrs_df.head(15)

In [112]:
sorted_hrs_df = clean_df.sort_values(by='Non_game_hours', ascending=False)
sorted_hrs_df.head(15)

clean_df = clean_df[clean_df['Non_game_hours'] <= 168]

In [113]:
clean_df = clean_df[(clean_df['Non_game_hours']+ clean_df['Hours']) <= 168]
# clean_df

### Save cleaned df in file to use in another notebook

In [114]:
clean_df.to_csv('../data/clean_data.csv')
# clean_df.head()