## Import & Inspect Data
*This data has already been explored, so some steps may appear to be skipped here. For more information, please see preliminary_analysis/data_cleaning.ipynb*

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
# Checking how the data is encoded to properly read it in the next step
import chardet

with open("../data/GamingStudy_data.csv", "rb") as f:
    print(chardet.detect(f.read(10000)))

{'encoding': 'ISO-8859-1', 'confidence': 0.03321167337449891, 'language': 'en', 'mime_type': 'text/plain'}

In [3]:
df = pd.read_csv('../data/GamingStudy_data.csv', encoding="ISO-8859-1")
df.head(3)

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,SWL2,SWL3,SWL4,SWL5,Game,Platform,Hours,earnings,whyplay,League,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU

In [4]:
df.info()

# I will be pulling S.No, Timestamp, GAD1-7, Game, Platform, Hours, whyplay (rename), Gender, 
# Age, Work, Degree, Residence, Playstyle, GAD_T, and Residence_ISO3 for this analysis.

<class 'pandas.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 55 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S. No.           13464 non-null  int64
 1   Timestamp        13464 non-null  float64
 2   GAD1             13464 non-null  int64
 3   GAD2             13464 non-null  int64
 4   GAD3             13464 non-null  int64
 5   GAD4             13464 non-null  int64
 6   GAD5             13464 non-null  int64
 7   GAD6             13464 non-null  int64
 8   GAD7             13464 non-null  int64
 9   GADE             12815 non-null  str
 10  SWL1             13464 non-null  int64
 11  SWL2             13464 non-null  int64
 12  SWL3             13464 non-null  int64
 13  SWL4             13464 non-null  int64
 14  SWL5             13464 non-null  int64
 15  Game             13464 non-null  str
 16  Platform         13464 non-null  str
 17  Hours            13434 non-null  float64
 18  earnings         13464 non-null  str
 19  whyplay          13464 non-null  str
 20  League           11612 non-null  str
 21  highestleague    0 non-null      float64
 22  streams          13364 non-null  float64
 23  SPIN1            13340 non-null  float64
 24  SPIN2            13310 non-null  float64
 25  SPIN3            13324 non-null  float64
 26  SPIN4            13305 non-null  float64
 27  SPIN5            13298 non-null  float64
 28  SPIN6            13308 non-null  float64
 29  SPIN7            13326 non-null  float64
 30  SPIN8            13320 non-null  float64
 31  SPIN9            13306 non-null  float64
 32  SPIN10           13304 non-null  float64
 33  SPIN11           13277 non-null  float64
 34  SPIN12           13296 non-null  float64
 35  SPIN13           13277 non-null  float64
 36  SPIN14           13308 non-null  float64
 37  SPIN15           13317 non-null  float64
 38  SPIN16           13317 non-null  float64
 39  SPIN17           13289 non-null  float64
 40  Narcissism       13441 non-null  float64
 41  Gender           13464 non-null  str
 42  Age              13464 non-null  int64
 43  Work             13426 non-null  str
 44  Degree           11887 non-null  str
 45  Birthplace       13464 non-null  str
 46  Residence        13464 non-null  str
 47  Reference        13449 non-null  str
 48  Playstyle        13464 non-null  str
 49  accept           13050 non-null  str
 50  GAD_T            13464 non-null  int64
 51  SWL_T            13464 non-null  int64
 52  SPIN_T           12814 non-null  float64
 53  Residence_ISO3   13354 non-null  str
 54  Birthplace_ISO3  13343 non-null  str
dtypes: float64(23), int64(16), str(16)
memory usage: 5.6 MB

## Fix Timestamp datatype
Only need the year for comparison

In [5]:
df['Date'] = pd.to_datetime(df['Timestamp'], unit='D', origin='1899-12-30').dt.year
df.head()

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,SWL2,SWL3,SWL4,SWL5,Game,Platform,Hours,earnings,whyplay,League,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3,Date
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA,2015
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA,2015
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU,2015
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20.0,I play for fun,improving,NaN,NaN,5.0,2.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,2.0,Male,28,Employed,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA,2015
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,having fun,NaN,NaN,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,Male,19,Employed,High school diploma (or equivalent),USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA,2015

## Create custom dataframe for analysis

In [6]:
gaming_GAD_df = df[['S. No.', 'Date', 'GAD1', 'GAD2', 'GAD3', 'GAD4', 'GAD5', 'GAD6', 'GAD7', 'GAD_T', 'Gender', 'Age', 'Work', 'Degree', 'Residence_ISO3', 'Game', 'Platform', 'Hours', 'whyplay', 'Playstyle']].copy()

gaming_GAD_df.head()

,S. No.,Date,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_T,Gender,Age,Work,Degree,Residence_ISO3,Game,Platform,Hours,whyplay,Playstyle
0,1,2015,0,0,0,0,1,0,0,1,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer
1,2,2015,1,2,2,2,0,1,0,8,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers
2,3,2015,0,2,2,0,0,3,1,8,Female,32,Employed,Bachelor (or equivalent),DEU,Other,PC,0.0,having fun,Singleplayer
3,4,2015,0,0,0,0,0,0,0,0,Male,28,Employed,Bachelor (or equivalent),USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...
4,5,2015,2,1,2,2,2,3,2,14,Male,19,Employed,High school diploma (or equivalent),KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers

In [7]:
gaming_GAD_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   S. No.          13464 non-null  int64
 1   Date            13464 non-null  int32
 2   GAD1            13464 non-null  int64
 3   GAD2            13464 non-null  int64
 4   GAD3            13464 non-null  int64
 5   GAD4            13464 non-null  int64
 6   GAD5            13464 non-null  int64
 7   GAD6            13464 non-null  int64
 8   GAD7            13464 non-null  int64
 9   GAD_T           13464 non-null  int64
 10  Gender          13464 non-null  str
 11  Age             13464 non-null  int64
 12  Work            13426 non-null  str
 13  Degree          11887 non-null  str
 14  Residence_ISO3  13354 non-null  str
 15  Game            13464 non-null  str
 16  Platform        13464 non-null  str
 17  Hours           13434 non-null  float64
 18  whyplay         13464 non-null  str
 19  Playstyle       13464 non-null  str
dtypes: float64(1), int32(1), int64(10), str(8)
memory usage: 2.0 MB

## Investigate null rows

In [8]:
gaming_GAD_df.isna().sum()

S. No.               0
Date                 0
GAD1                 0
GAD2                 0
GAD3                 0
GAD4                 0
GAD5                 0
GAD6                 0
GAD7                 0
GAD_T                0
Gender               0
Age                  0
Work                38
Degree            1577
Residence_ISO3     110
Game                 0
Platform             0
Hours               30
whyplay              0
Playstyle            0
dtype: int64

In [9]:
gaming_GAD_df.shape

(13464, 20)

### Drop 30 na Hours rows to keep int datatype

In [10]:
gaming_GAD_df = gaming_GAD_df.dropna(subset=['Hours'])
gaming_GAD_df.shape

(13434, 20)

### Fill na Degree and Work with 'unknown'

In [11]:
gaming_GAD_df[['Degree', 'Work']] = gaming_GAD_df[['Degree', 'Work']].fillna('Unknown')
gaming_GAD_df.isna().sum()

S. No.              0
Date                0
GAD1                0
GAD2                0
GAD3                0
GAD4                0
GAD5                0
GAD6                0
GAD7                0
GAD_T               0
Gender              0
Age                 0
Work                0
Degree              0
Residence_ISO3    110
Game                0
Platform            0
Hours               0
whyplay             0
Playstyle           0
dtype: int64

### Investigate Residence_ISO3 na values

In [12]:
gaming_GAD_df[gaming_GAD_df[['Residence_ISO3']].isna().any(axis=1)].head()

# na is returned when residence is unknown.

,S. No.,Date,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_T,Gender,Age,Work,Degree,Residence_ISO3,Game,Platform,Hours,whyplay,Playstyle
173,180,2015,0,2,0,0,0,3,0,5,Male,19,Student at college / university,Unknown,NaN,League of Legends,PC,7.0,improving,Multiplayer - online - with real life friends
354,376,2015,0,1,1,0,0,0,0,2,Male,35,Employed,Master (or equivalent),NaN,Starcraft 2,PC,14.0,having fun,Multiplayer - online - with strangers
437,462,2015,0,0,0,0,0,0,0,0,Male,24,Employed,High school diploma (or equivalent),NaN,League of Legends,PC,40.0,improving,Multiplayer - online - with strangers
682,725,2015,3,3,2,2,3,3,0,16,Male,20,Unemployed / between jobs,Unknown,NaN,League of Legends,PC,17.0,having fun,Multiplayer - online - with real life friends
751,797,2015,1,0,0,0,1,2,1,5,Male,18,Student at school,High school diploma (or equivalent),NaN,League of Legends,PC,35.0,winning,Multiplayer - online - with strangers

#### Remove 140 unknown rows in 'Residence'

In [ ]:
gaming_GAD_df = gaming_GAD_df.dropna(subset='Residence_ISO3')
gaming_GAD_df.shape

(13324, 20)

In [14]:
gaming_GAD_df.isna().sum()

S. No.            0
Date              0
GAD1              0
GAD2              0
GAD3              0
GAD4              0
GAD5              0
GAD6              0
GAD7              0
GAD_T             0
Gender            0
Age               0
Work              0
Degree            0
Residence_ISO3    0
Game              0
Platform          0
Hours             0
whyplay           0
Playstyle         0
dtype: int64

## Investigate outliers in 'Hours'

There are 168 hours in a week. I will be filtering out any values that exceed this number and note the high outliers as they did not account for sleep. The same will apply to the non-game hours column.

I will also remove any rows where 'Hours' + 'Non-game-hours' > 168.

Rows removed: 7

In [15]:
gaming_GAD_df = gaming_GAD_df[gaming_GAD_df['Hours'] <=168]

In [16]:
# Check highest hour rows
sorted_hours_df = gaming_GAD_df.sort_values(by='Hours', ascending=False)
sorted_hours_df

,S. No.,Date,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_T,Gender,Age,Work,Degree,Residence_ISO3,Game,Platform,Hours,whyplay,Playstyle
7615,8024,2015,3,0,0,3,3,3,0,12,Male,19,Employed,Bachelor (or equivalent),CAN,Other,PC,140.0,Sexual thrill,Singleplayer
3112,3267,2015,3,3,3,3,3,3,3,21,Female,22,Employed,Bachelor (or equivalent),FRA,Other,"Console (PS, Xbox, ...)",140.0,winning,Multiplayer - online - with real life friends
611,653,2015,2,3,3,3,3,3,0,17,Male,23,Employed,High school diploma (or equivalent),FRA,League of Legends,PC,120.0,improving,Multiplayer - online - with strangers
4069,4268,2015,1,0,0,0,0,2,0,3,Male,19,Unemployed / between jobs,Unknown,PHL,League of Legends,PC,120.0,improving,Multiplayer - online - with online acquaintanc...
4363,4575,2015,0,0,0,0,0,0,0,0,Male,18,Unemployed / between jobs,Unknown,FRA,League of Legends,PC,120.0,winning,Singleplayer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,11981,2015,1,1,1,1,0,0,0,4,Male,19,Student at college / university,High school diploma (or equivalent),FRA,League of Legends,PC,0.0,having fun,Multiplayer - online - with real life friends
12779,13535,2015,0,0,0,0,0,0,0,0,Male,20,Student at college / university,High school diploma (or equivalent),PAK,League of Legends,PC,0.0,having fun,Multiplayer - online - with strangers
58,61,2015,3,3,1,1,0,1,0,9,Male,19,Student at college / university,Unknown,CAN,Other,PC,0.0,having fun,Singleplayer
54,56,2015,2,1,1,3,1,2,0,10,Male,19,Student at college / university,High school diploma (or equivalent),USA,Other,PC,0.0,having fun,Singleplayer
8821,9295,2015,1,0,0,0,1,0,0,2,Male,19,Student at college / university,High school diploma (or equivalent),DEU,League of Legends,PC,0.0,winning,"Duo Queue with one good friend, else solo"

In [17]:
gaming_GAD_df.info()

<class 'pandas.DataFrame'>
Index: 13324 entries, 0 to 13463
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   S. No.          13324 non-null  int64
 1   Date            13324 non-null  int32
 2   GAD1            13324 non-null  int64
 3   GAD2            13324 non-null  int64
 4   GAD3            13324 non-null  int64
 5   GAD4            13324 non-null  int64
 6   GAD5            13324 non-null  int64
 7   GAD6            13324 non-null  int64
 8   GAD7            13324 non-null  int64
 9   GAD_T           13324 non-null  int64
 10  Gender          13324 non-null  str
 11  Age             13324 non-null  int64
 12  Work            13324 non-null  str
 13  Degree          13324 non-null  str
 14  Residence_ISO3  13324 non-null  str
 15  Game            13324 non-null  str
 16  Platform        13324 non-null  str
 17  Hours           13324 non-null  float64
 18  whyplay         13324 non-null  str
 19  Playstyle       13324 non-null  str
dtypes: float64(1), int32(1), int64(10), str(8)
memory usage: 2.1 MB

### Remove 'work' column
Other dataset does not have enough information for comparative analysis

In [18]:
gaming_GAD_df = gaming_GAD_df.drop(columns='Work')
gaming_GAD_df.info()

<class 'pandas.DataFrame'>
Index: 13324 entries, 0 to 13463
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   S. No.          13324 non-null  int64
 1   Date            13324 non-null  int32
 2   GAD1            13324 non-null  int64
 3   GAD2            13324 non-null  int64
 4   GAD3            13324 non-null  int64
 5   GAD4            13324 non-null  int64
 6   GAD5            13324 non-null  int64
 7   GAD6            13324 non-null  int64
 8   GAD7            13324 non-null  int64
 9   GAD_T           13324 non-null  int64
 10  Gender          13324 non-null  str
 11  Age             13324 non-null  int64
 12  Degree          13324 non-null  str
 13  Residence_ISO3  13324 non-null  str
 14  Game            13324 non-null  str
 15  Platform        13324 non-null  str
 16  Hours           13324 non-null  float64
 17  whyplay         13324 non-null  str
 18  Playstyle       13324 non-null  str
dtypes: float64(1), int32(1), int64(10), str(7)
memory usage: 2.0 MB

## Rename columns to match other dataset

In [19]:
gaming_GAD_df = gaming_GAD_df.rename(columns={
    "S. No." : "participant_id",
    "Date" : "year", 
    "GAD_T" : "GAD_total",
    "Age" : "age",
    "Residence_ISO3" : "residence",
    "Game" : "game",
    "Platform" : "platform",
    "Hours" : "hours",
    "whyplay" : "reason",
    "Playstyle" : "playstyle"
})

gaming_GAD_df.info()

<class 'pandas.DataFrame'>
Index: 13324 entries, 0 to 13463
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   participant_id  13324 non-null  int64
 1   year            13324 non-null  int32
 2   GAD1            13324 non-null  int64
 3   GAD2            13324 non-null  int64
 4   GAD3            13324 non-null  int64
 5   GAD4            13324 non-null  int64
 6   GAD5            13324 non-null  int64
 7   GAD6            13324 non-null  int64
 8   GAD7            13324 non-null  int64
 9   GAD_total       13324 non-null  int64
 10  Gender          13324 non-null  str
 11  age             13324 non-null  int64
 12  Degree          13324 non-null  str
 13  residence       13324 non-null  str
 14  game            13324 non-null  str
 15  platform        13324 non-null  str
 16  hours           13324 non-null  float64
 17  reason          13324 non-null  str
 18  playstyle       13324 non-null  str
dtypes: float64(1), int32(1), int64(10), str(7)
memory usage: 2.0 MB

## Calculate and add missing columns

### GAD_cat column calculation and relocation

In [20]:
# categories from both NIHS codebook

total = gaming_GAD_df['GAD_total']
condlist = [
    total < 5,
    (total >= 5) & (total < 10),
    (total >= 10) & (total < 15),
    total >= 15
]
choicelist = [1, 2, 3, 4]

gaming_GAD_df['GAD_cat'] = np.select(condlist, choicelist, default=8)

gaming_GAD_df.head()

# Resources:
#   https://www.geeksforgeeks.org/python/numpy-select-function-python/
#   https://medium.com/@michalwesleymnach/the-complete-guide-to-create-columns-based-on-multiple-conditions-in-pandas-dataframes-eedf2c0392a6

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,Gender,age,Degree,residence,game,platform,hours,reason,playstyle,GAD_cat
0,1,2015,0,0,0,0,1,0,0,1,Male,25,Bachelor (or equivalent),USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer,1
1,2,2015,1,2,2,2,0,1,0,8,Male,41,Bachelor (or equivalent),USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers,2
2,3,2015,0,2,2,0,0,3,1,8,Female,32,Bachelor (or equivalent),DEU,Other,PC,0.0,having fun,Singleplayer,2
3,4,2015,0,0,0,0,0,0,0,0,Male,28,Bachelor (or equivalent),USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...,1
4,5,2015,2,1,2,2,2,3,2,14,Male,19,High school diploma (or equivalent),KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers,3

In [21]:
col_to_move = gaming_GAD_df.pop('GAD_cat')
gaming_GAD_df.insert(10, 'GAD_cat', col_to_move)
gaming_GAD_df.head()

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,Gender,age,Degree,residence,game,platform,hours,reason,playstyle
0,1,2015,0,0,0,0,1,0,0,1,1,Male,25,Bachelor (or equivalent),USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer
1,2,2015,1,2,2,2,0,1,0,8,2,Male,41,Bachelor (or equivalent),USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers
2,3,2015,0,2,2,0,0,3,1,8,2,Female,32,Bachelor (or equivalent),DEU,Other,PC,0.0,having fun,Singleplayer
3,4,2015,0,0,0,0,0,0,0,0,1,Male,28,Bachelor (or equivalent),USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...
4,5,2015,2,1,2,2,2,3,2,14,3,Male,19,High school diploma (or equivalent),KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers

### education_id calculation and relocation

**Gaming data**
|Code | Description|
|---|---|
|08	| 'Bachelor (or equivalent)',|
|12	| 'High school diploma (or equivalent)',|
|13	| 'Ph.D., Psy. D., MD (or equivalent)',|
|09	| 'Master\xa0(or equivalent)',|
|99	| 'Unknown'|


**NIHS data:**
|Code 	    |Description 								                        |
| ---       | ---                                                               | 
|00 	    |Never attended/kindergarten only 		                            |
|01 	    |Grade 1-11								                            |
|02 	    |12th grade, no diploma 				                            |
|03 	    |GED or equivalent 						                            |
|04 	    |High School Graduate 					                            |
|05 	    |Some college, no degree 5				                            |
|06 	    |Associate degree: occupational, technical, or vocational program   |
|07 	    |Associate degree: academic program 			                    |
|08 	    |Bachelor's degree (Example: BA, AB, BS, BBA)                       |
|09 	    |Master's degree (Example: MA, MS, MEng, MEd, MBA)                  |
|10 	    |Professional School degree (Example: MD, DDS, DVM, JD)             |
|11 	    |Doctoral degree (Example: PhD, EdD) 		                        |
|97 	    |Refused 								                            |
|98 	    |Not Ascertained 							                        |
|99 	    |Don't Know 								                        |

In [22]:
# Identify each degree option found in the data

gaming_GAD_df['Degree'].unique().tolist()

['Bachelor\xa0(or equivalent)',
 'High school diploma (or equivalent)',
 'Ph.D., Psy. D., MD (or equivalent)',
 'Master\xa0(or equivalent)',
 'Unknown']

In [23]:
condlist_ed = [
    gaming_GAD_df['Degree'] == 'Bachelor\xa0(or equivalent)',
    gaming_GAD_df['Degree'] == 'High school diploma (or equivalent)',
    gaming_GAD_df['Degree'] == 'Ph.D., Psy. D., MD (or equivalent)',
    gaming_GAD_df['Degree'] == 'Master\xa0(or equivalent)',
    gaming_GAD_df['Degree'] == 'Unknown'
]
choicelist_ed = [8, 12, 13, 9, 99]

gaming_GAD_df['education_id'] = np.select(condlist_ed, choicelist_ed, default=99)

gaming_GAD_df.head()

# I used ChatGPT to learn how to run the condlist_ed as a boolean check rather than
# listing the values alone.

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,Gender,age,Degree,residence,game,platform,hours,reason,playstyle,education_id
0,1,2015,0,0,0,0,1,0,0,1,1,Male,25,Bachelor (or equivalent),USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer,8
1,2,2015,1,2,2,2,0,1,0,8,2,Male,41,Bachelor (or equivalent),USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers,8
2,3,2015,0,2,2,0,0,3,1,8,2,Female,32,Bachelor (or equivalent),DEU,Other,PC,0.0,having fun,Singleplayer,8
3,4,2015,0,0,0,0,0,0,0,0,1,Male,28,Bachelor (or equivalent),USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...,8
4,5,2015,2,1,2,2,2,3,2,14,3,Male,19,High school diploma (or equivalent),KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers,12

In [24]:
# Move education_id column
col_to_move = gaming_GAD_df.pop('education_id')
gaming_GAD_df.insert(14, 'education_id', col_to_move)
gaming_GAD_df.head()

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,Gender,age,Degree,education_id,residence,game,platform,hours,reason,playstyle
0,1,2015,0,0,0,0,1,0,0,1,1,Male,25,Bachelor (or equivalent),8,USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer
1,2,2015,1,2,2,2,0,1,0,8,2,Male,41,Bachelor (or equivalent),8,USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers
2,3,2015,0,2,2,0,0,3,1,8,2,Female,32,Bachelor (or equivalent),8,DEU,Other,PC,0.0,having fun,Singleplayer
3,4,2015,0,0,0,0,0,0,0,0,1,Male,28,Bachelor (or equivalent),8,USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...
4,5,2015,2,1,2,2,2,3,2,14,3,Male,19,High school diploma (or equivalent),12,KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers

### sex_id calcluation and relocation
Table below from NHIS codebook
| Code | Description     | 
| ---  | ---             |
| 1    | Male            |
| 2    | Female          |
| 7    | Refused         |
| 8    | Not Ascertained |
| 9    | Don't Know      |

Will add
| Code | Description     | 
| ---  | ---             |
| 3    | Other           |

In [25]:
# Identify each gender/sex option found in the data

gaming_GAD_df['Gender'].unique().tolist()

['Male', 'Female', 'Other']

In [26]:
condlist_sex = [
    gaming_GAD_df['Gender'] == 'Male',
    gaming_GAD_df['Gender'] == 'Female',
    gaming_GAD_df['Gender'] == 'Other'
]
choicelist_sex = [1, 2, 3]

gaming_GAD_df['sex_id'] = np.select(condlist_sex, choicelist_sex, default=9)

gaming_GAD_df.head()

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,Gender,age,Degree,education_id,residence,game,platform,hours,reason,playstyle,sex_id
0,1,2015,0,0,0,0,1,0,0,1,1,Male,25,Bachelor (or equivalent),8,USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer,1
1,2,2015,1,2,2,2,0,1,0,8,2,Male,41,Bachelor (or equivalent),8,USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers,1
2,3,2015,0,2,2,0,0,3,1,8,2,Female,32,Bachelor (or equivalent),8,DEU,Other,PC,0.0,having fun,Singleplayer,2
3,4,2015,0,0,0,0,0,0,0,0,1,Male,28,Bachelor (or equivalent),8,USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...,1
4,5,2015,2,1,2,2,2,3,2,14,3,Male,19,High school diploma (or equivalent),12,KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers,1

In [27]:
# Move sex_id column
col_to_move = gaming_GAD_df.pop('sex_id')
gaming_GAD_df.insert(12, 'sex_id', col_to_move)
gaming_GAD_df.head()

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,Gender,sex_id,age,Degree,education_id,residence,game,platform,hours,reason,playstyle
0,1,2015,0,0,0,0,1,0,0,1,1,Male,1,25,Bachelor (or equivalent),8,USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer
1,2,2015,1,2,2,2,0,1,0,8,2,Male,1,41,Bachelor (or equivalent),8,USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers
2,3,2015,0,2,2,0,0,3,1,8,2,Female,2,32,Bachelor (or equivalent),8,DEU,Other,PC,0.0,having fun,Singleplayer
3,4,2015,0,0,0,0,0,0,0,0,1,Male,1,28,Bachelor (or equivalent),8,USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...
4,5,2015,2,1,2,2,2,3,2,14,3,Male,1,19,High school diploma (or equivalent),12,KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers

In [28]:
# Move Gender and Degree  columns to end
col_to_move = gaming_GAD_df.pop('Gender')
gaming_GAD_df.insert(21, 'Gender', col_to_move)

col_to_move = gaming_GAD_df.pop('Degree')
gaming_GAD_df.insert(12, 'Degree', col_to_move)


gaming_GAD_df.head()

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,sex_id,Degree,age,education_id,residence,game,platform,hours,reason,playstyle,Gender
0,1,2015,0,0,0,0,1,0,0,1,1,1,Bachelor (or equivalent),25,8,USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer,Male
1,2,2015,1,2,2,2,0,1,0,8,2,1,Bachelor (or equivalent),41,8,USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers,Male
2,3,2015,0,2,2,0,0,3,1,8,2,2,Bachelor (or equivalent),32,8,DEU,Other,PC,0.0,having fun,Singleplayer,Female
3,4,2015,0,0,0,0,0,0,0,0,1,1,Bachelor (or equivalent),28,8,USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...,Male
4,5,2015,2,1,2,2,2,3,2,14,3,1,High school diploma (or equivalent),19,12,KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers,Male

### Add survey_id = 1 column

In [29]:
gaming_GAD_df['survey_id'] = 1
gaming_GAD_df.head()

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,sex_id,Degree,age,education_id,residence,game,platform,hours,reason,playstyle,Gender,survey_id
0,1,2015,0,0,0,0,1,0,0,1,1,1,Bachelor (or equivalent),25,8,USA,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Singleplayer,Male,1
1,2,2015,1,2,2,2,0,1,0,8,2,1,Bachelor (or equivalent),41,8,USA,Other,PC,8.0,having fun,Multiplayer - online - with strangers,Male,1
2,3,2015,0,2,2,0,0,3,1,8,2,2,Bachelor (or equivalent),32,8,DEU,Other,PC,0.0,having fun,Singleplayer,Female,1
3,4,2015,0,0,0,0,0,0,0,0,1,1,Bachelor (or equivalent),28,8,USA,Other,PC,20.0,improving,Multiplayer - online - with online acquaintanc...,Male,1
4,5,2015,2,1,2,2,2,3,2,14,3,1,High school diploma (or equivalent),19,12,KOR,Other,"Console (PS, Xbox, ...)",20.0,having fun,Multiplayer - online - with strangers,Male,1

### Put survey_id in same index on both dataframes

In [30]:
col_to_move = gaming_GAD_df.pop('survey_id')
gaming_GAD_df.insert(14, 'survey_id', col_to_move)

## Save cleaned data to csv

In [31]:
gaming_GAD_df.info()

<class 'pandas.DataFrame'>
Index: 13324 entries, 0 to 13463
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   participant_id  13324 non-null  int64
 1   year            13324 non-null  int32
 2   GAD1            13324 non-null  int64
 3   GAD2            13324 non-null  int64
 4   GAD3            13324 non-null  int64
 5   GAD4            13324 non-null  int64
 6   GAD5            13324 non-null  int64
 7   GAD6            13324 non-null  int64
 8   GAD7            13324 non-null  int64
 9   GAD_total       13324 non-null  int64
 10  GAD_cat         13324 non-null  int64
 11  sex_id          13324 non-null  int64
 12  Degree          13324 non-null  str
 13  age             13324 non-null  int64
 14  survey_id       13324 non-null  int64
 15  education_id    13324 non-null  int64
 16  residence       13324 non-null  str
 17  game            13324 non-null  str
 18  platform        13324 non-null  str
 19  hours           13324 non-null  float64
 20  reason          13324 non-null  str
 21  playstyle       13324 non-null  str
 22  Gender          13324 non-null  str
dtypes: float64(1), int32(1), int64(14), str(7)
memory usage: 2.4 MB

In [32]:
gaming_GAD_df.to_csv('../data/gaming_GAD_CLEAN.csv')

### Exploring why there are multiple ids of 43...
I will return to this after correcting the NHIS GAD scores and datatyping

**UPDATE**: After fixing data issues, this duplicate dissappered

In [33]:
filtered_data = gaming_GAD_df.loc[gaming_GAD_df['participant_id'] == 43]
filtered_data

,participant_id,year,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_total,GAD_cat,sex_id,Degree,age,survey_id,education_id,residence,game,platform,hours,reason,playstyle,Gender
42,43,2015,0,0,0,0,0,0,0,0,1,1,Bachelor (or equivalent),27,1,8,USA,Other,PC,12.0,having fun,Multiplayer - online - with strangers,Male

### Re-type GAD_cat and ids as dtype="category"

In [35]:
gaming_GAD_df[['participant_id', 'GAD_cat', 'sex_id', 'education_id', 'survey_id']] = gaming_GAD_df[['participant_id', 'GAD_cat', 'sex_id', 'education_id', 'survey_id']].astype('category')
gaming_GAD_df.info()

<class 'pandas.DataFrame'>
Index: 13324 entries, 0 to 13463
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   participant_id  13324 non-null  category
 1   year            13324 non-null  int32
 2   GAD1            13324 non-null  int64
 3   GAD2            13324 non-null  int64
 4   GAD3            13324 non-null  int64
 5   GAD4            13324 non-null  int64
 6   GAD5            13324 non-null  int64
 7   GAD6            13324 non-null  int64
 8   GAD7            13324 non-null  int64
 9   GAD_total       13324 non-null  int64
 10  GAD_cat         13324 non-null  category
 11  sex_id          13324 non-null  category
 12  Degree          13324 non-null  str
 13  age             13324 non-null  int64
 14  survey_id       13324 non-null  category
 15  education_id    13324 non-null  category
 16  residence       13324 non-null  str
 17  game            13324 non-null  str
 18  platform        13324 non-null  str
 19  hours           13324 non-null  float64
 20  reason          13324 non-null  str
 21  playstyle       13324 non-null  str
 22  Gender          13324 non-null  str
dtypes: category(5), float64(1), int32(1), int64(9), str(7)
memory usage: 2.1 MB

## Save updated data to csv

In [36]:
gaming_GAD_df.to_csv('../data/gaming_GAD_CLEAN.csv')