## Import & Inspect Data
*This data has already been explored, so some steps may appear to be skipped here. For more information, please see preliminary_analysis/data_cleaning.ipynb*

In [19]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [20]:
# Checking how the data is encoded to properly read it in the next step
import chardet

with open("../data/GamingStudy_data.csv", "rb") as f:
    print(chardet.detect(f.read(10000)))

{'encoding': 'ISO-8859-1', 'confidence': 0.03321167337449891, 'language': 'en', 'mime_type': 'text/plain'}

In [21]:
df = pd.read_csv('../data/GamingStudy_data.csv', encoding="ISO-8859-1")
df.head(3)

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,SWL2,SWL3,SWL4,SWL5,Game,Platform,Hours,earnings,whyplay,League,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU

In [22]:
df.info()

# I will be pulling S.No, Timestamp, GAD1-7, Game, Platform, Hours, whyplay (rename), Gender, 
# Age, Work, Degree, Residence, Playstyle, GAD_T, and Residence_ISO3 for this analysis.

<class 'pandas.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 55 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   S. No.           13464 non-null  int64
 1   Timestamp        13464 non-null  float64
 2   GAD1             13464 non-null  int64
 3   GAD2             13464 non-null  int64
 4   GAD3             13464 non-null  int64
 5   GAD4             13464 non-null  int64
 6   GAD5             13464 non-null  int64
 7   GAD6             13464 non-null  int64
 8   GAD7             13464 non-null  int64
 9   GADE             12815 non-null  str
 10  SWL1             13464 non-null  int64
 11  SWL2             13464 non-null  int64
 12  SWL3             13464 non-null  int64
 13  SWL4             13464 non-null  int64
 14  SWL5             13464 non-null  int64
 15  Game             13464 non-null  str
 16  Platform         13464 non-null  str
 17  Hours            13434 non-null  float64
 18  earnings         13464 non-null  str
 19  whyplay          13464 non-null  str
 20  League           11612 non-null  str
 21  highestleague    0 non-null      float64
 22  streams          13364 non-null  float64
 23  SPIN1            13340 non-null  float64
 24  SPIN2            13310 non-null  float64
 25  SPIN3            13324 non-null  float64
 26  SPIN4            13305 non-null  float64
 27  SPIN5            13298 non-null  float64
 28  SPIN6            13308 non-null  float64
 29  SPIN7            13326 non-null  float64
 30  SPIN8            13320 non-null  float64
 31  SPIN9            13306 non-null  float64
 32  SPIN10           13304 non-null  float64
 33  SPIN11           13277 non-null  float64
 34  SPIN12           13296 non-null  float64
 35  SPIN13           13277 non-null  float64
 36  SPIN14           13308 non-null  float64
 37  SPIN15           13317 non-null  float64
 38  SPIN16           13317 non-null  float64
 39  SPIN17           13289 non-null  float64
 40  Narcissism       13441 non-null  float64
 41  Gender           13464 non-null  str
 42  Age              13464 non-null  int64
 43  Work             13426 non-null  str
 44  Degree           11887 non-null  str
 45  Birthplace       13464 non-null  str
 46  Residence        13464 non-null  str
 47  Reference        13449 non-null  str
 48  Playstyle        13464 non-null  str
 49  accept           13050 non-null  str
 50  GAD_T            13464 non-null  int64
 51  SWL_T            13464 non-null  int64
 52  SPIN_T           12814 non-null  float64
 53  Residence_ISO3   13354 non-null  str
 54  Birthplace_ISO3  13343 non-null  str
dtypes: float64(23), int64(16), str(16)
memory usage: 5.6 MB

## Fix Timestamp datatype

In [23]:
df['Date'] = pd.to_datetime(df['Timestamp'], unit='D', origin='1899-12-30').dt.normalize()
df.head()

,S. No.,Timestamp,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GADE,SWL1,SWL2,SWL3,SWL4,SWL5,Game,Platform,Hours,earnings,whyplay,League,highestleague,streams,SPIN1,SPIN2,SPIN3,SPIN4,SPIN5,SPIN6,SPIN7,SPIN8,SPIN9,SPIN10,SPIN11,SPIN12,SPIN13,SPIN14,SPIN15,SPIN16,SPIN17,Narcissism,Gender,Age,Work,Degree,Birthplace,Residence,Reference,Playstyle,accept,GAD_T,SWL_T,SPIN_T,Residence_ISO3,Birthplace_ISO3,Date
0,1,42052.00437,0,0,0,0,1,0,0,Not difficult at all,3,5,5,5,5,Skyrim,"Console (PS, Xbox, ...)",15.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Singleplayer,Accept,1,23,5.0,USA,USA,2015-02-17
1,2,42052.00680,1,2,2,2,0,1,0,Somewhat difficult,3,5,2,5,1,Other,PC,8.0,I play for fun,having fun,NaN,NaN,2.0,2.0,1.0,1.0,3.0,2.0,3.0,1.0,3.0,4.0,0.0,3.0,0.0,1.0,3.0,3.0,1.0,2.0,1.0,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with strangers,Accept,8,16,33.0,USA,USA,2015-02-17
2,3,42052.03860,0,2,2,0,0,3,1,Not difficult at all,2,6,5,2,2,Other,PC,0.0,I play for fun,having fun,NaN,NaN,0.0,1.0,0.0,1.0,2.0,3.0,4.0,2.0,1.0,0.0,1.0,1.0,3.0,0.0,2.0,4.0,4.0,2.0,4.0,Female,32,Employed,Bachelor (or equivalent),Germany,Germany,Reddit,Singleplayer,Accept,8,17,31.0,DEU,DEU,2015-02-17
3,4,42052.06804,0,0,0,0,0,0,0,Not difficult at all,2,5,5,3,2,Other,PC,20.0,I play for fun,improving,NaN,NaN,5.0,2.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,2.0,Male,28,Employed,Bachelor (or equivalent),USA,USA,Reddit,Multiplayer - online - with online acquaintanc...,Accept,0,17,11.0,USA,USA,2015-02-17
4,5,42052.08948,2,1,2,2,2,3,2,Very difficult,2,2,4,5,1,Other,"Console (PS, Xbox, ...)",20.0,I play for fun,having fun,NaN,NaN,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,Male,19,Employed,High school diploma (or equivalent),USA,South Korea,Reddit,Multiplayer - online - with strangers,Accept,14,14,13.0,KOR,USA,2015-02-17

## Create custom dataframe for analysis

In [24]:
gaming_GAD_df = df[['S. No.', 'Date', 'GAD1', 'GAD2', 'GAD3', 'GAD4', 'GAD5', 'GAD6', 'GAD7', 'GAD_T', 'Game', 'Platform', 'Hours', 'whyplay', 'Gender', 'Age', 'Work', 'Degree', 'Residence', 'Residence_ISO3', 'Playstyle']].copy()

gaming_GAD_df.head()

,S. No.,Date,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_T,Game,Platform,Hours,whyplay,Gender,Age,Work,Degree,Residence,Residence_ISO3,Playstyle
0,1,2015-02-17,0,0,0,0,1,0,0,1,Skyrim,"Console (PS, Xbox, ...)",15.0,having fun,Male,25,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Singleplayer
1,2,2015-02-17,1,2,2,2,0,1,0,8,Other,PC,8.0,having fun,Male,41,Unemployed / between jobs,Bachelor (or equivalent),USA,USA,Multiplayer - online - with strangers
2,3,2015-02-17,0,2,2,0,0,3,1,8,Other,PC,0.0,having fun,Female,32,Employed,Bachelor (or equivalent),Germany,DEU,Singleplayer
3,4,2015-02-17,0,0,0,0,0,0,0,0,Other,PC,20.0,improving,Male,28,Employed,Bachelor (or equivalent),USA,USA,Multiplayer - online - with online acquaintanc...
4,5,2015-02-17,2,1,2,2,2,3,2,14,Other,"Console (PS, Xbox, ...)",20.0,having fun,Male,19,Employed,High school diploma (or equivalent),South Korea,KOR,Multiplayer - online - with strangers

In [25]:
gaming_GAD_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13464 entries, 0 to 13463
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   S. No.          13464 non-null  int64
 1   Date            13464 non-null  datetime64[ns]
 2   GAD1            13464 non-null  int64
 3   GAD2            13464 non-null  int64
 4   GAD3            13464 non-null  int64
 5   GAD4            13464 non-null  int64
 6   GAD5            13464 non-null  int64
 7   GAD6            13464 non-null  int64
 8   GAD7            13464 non-null  int64
 9   GAD_T           13464 non-null  int64
 10  Game            13464 non-null  str
 11  Platform        13464 non-null  str
 12  Hours           13434 non-null  float64
 13  whyplay         13464 non-null  str
 14  Gender          13464 non-null  str
 15  Age             13464 non-null  int64
 16  Work            13426 non-null  str
 17  Degree          11887 non-null  str
 18  Residence       13464 non-null  str
 19  Residence_ISO3  13354 non-null  str
 20  Playstyle       13464 non-null  str
dtypes: datetime64[ns](1), float64(1), int64(10), str(9)
memory usage: 2.2 MB

## Investigate null rows

In [26]:
gaming_GAD_df.isna().sum()

S. No.               0
Date                 0
GAD1                 0
GAD2                 0
GAD3                 0
GAD4                 0
GAD5                 0
GAD6                 0
GAD7                 0
GAD_T                0
Game                 0
Platform             0
Hours               30
whyplay              0
Gender               0
Age                  0
Work                38
Degree            1577
Residence            0
Residence_ISO3     110
Playstyle            0
dtype: int64

In [27]:
gaming_GAD_df.shape

(13464, 21)

### Drop 30 na Hours rows to keep int datatype

In [28]:
gaming_GAD_df = gaming_GAD_df.dropna(subset=['Hours'])
gaming_GAD_df.shape

(13434, 21)

### Fill na Degree and Work with 'unknown'

In [29]:
gaming_GAD_df[['Degree', 'Work']] = gaming_GAD_df[['Degree', 'Work']].fillna('Unknown')
gaming_GAD_df.isna().sum()

S. No.              0
Date                0
GAD1                0
GAD2                0
GAD3                0
GAD4                0
GAD5                0
GAD6                0
GAD7                0
GAD_T               0
Game                0
Platform            0
Hours               0
whyplay             0
Gender              0
Age                 0
Work                0
Degree              0
Residence           0
Residence_ISO3    110
Playstyle           0
dtype: int64

### Investigate Residence_ISO3 na values

In [30]:
gaming_GAD_df[gaming_GAD_df[['Residence_ISO3']].isna().any(axis=1)].head()

# na is returned when residence is unknown.

,S. No.,Date,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_T,Game,Platform,Hours,whyplay,Gender,Age,Work,Degree,Residence,Residence_ISO3,Playstyle
173,180,2015-02-19,0,2,0,0,0,3,0,5,League of Legends,PC,7.0,improving,Male,19,Student at college / university,Unknown,Unknown,NaN,Multiplayer - online - with real life friends
354,376,2015-02-19,0,1,1,0,0,0,0,2,Starcraft 2,PC,14.0,having fun,Male,35,Employed,Master (or equivalent),Unknown,NaN,Multiplayer - online - with strangers
437,462,2015-02-19,0,0,0,0,0,0,0,0,League of Legends,PC,40.0,improving,Male,24,Employed,High school diploma (or equivalent),Unknown,NaN,Multiplayer - online - with strangers
682,725,2015-02-19,3,3,2,2,3,3,0,16,League of Legends,PC,17.0,having fun,Male,20,Unemployed / between jobs,Unknown,Unknown,NaN,Multiplayer - online - with real life friends
751,797,2015-02-19,1,0,0,0,1,2,1,5,League of Legends,PC,35.0,winning,Male,18,Student at school,High school diploma (or equivalent),Unknown,NaN,Multiplayer - online - with strangers

#### Remove unknown rows in 'Residence'

In [31]:
gaming_GAD_df = gaming_GAD_df.dropna(subset='Residence_ISO3')
gaming_GAD_df.shape

(13324, 21)

In [32]:
gaming_GAD_df.isna().sum()

S. No.            0
Date              0
GAD1              0
GAD2              0
GAD3              0
GAD4              0
GAD5              0
GAD6              0
GAD7              0
GAD_T             0
Game              0
Platform          0
Hours             0
whyplay           0
Gender            0
Age               0
Work              0
Degree            0
Residence         0
Residence_ISO3    0
Playstyle         0
dtype: int64

## Investigate outliers in 'Hours'

There are 168 hours in a week. I will be filtering out any values that exceed this number and note the high outliers as they did not account for sleep. The same will apply to the non-game hours column.

I will also remove any rows where 'Hours' + 'Non-game-hours' > 168.

Rows removed: 7

In [33]:
gaming_GAD_df = gaming_GAD_df[gaming_GAD_df['Hours'] <=168]

In [34]:
# Check highest hour rows
sorted_hours_df = gaming_GAD_df.sort_values(by='Hours', ascending=False)
sorted_hours_df

,S. No.,Date,GAD1,GAD2,GAD3,GAD4,GAD5,GAD6,GAD7,GAD_T,Game,Platform,Hours,whyplay,Gender,Age,Work,Degree,Residence,Residence_ISO3,Playstyle
7615,8024,2015-02-19,3,0,0,3,3,3,0,12,Other,PC,140.0,Sexual thrill,Male,19,Employed,Bachelor (or equivalent),Canada,CAN,Singleplayer
3112,3267,2015-02-19,3,3,3,3,3,3,3,21,Other,"Console (PS, Xbox, ...)",140.0,winning,Female,22,Employed,Bachelor (or equivalent),France,FRA,Multiplayer - online - with real life friends
611,653,2015-02-19,2,3,3,3,3,3,0,17,League of Legends,PC,120.0,improving,Male,23,Employed,High school diploma (or equivalent),France,FRA,Multiplayer - online - with strangers
4069,4268,2015-02-19,1,0,0,0,0,2,0,3,League of Legends,PC,120.0,improving,Male,19,Unemployed / between jobs,Unknown,Philippines,PHL,Multiplayer - online - with online acquaintanc...
4363,4575,2015-02-19,0,0,0,0,0,0,0,0,League of Legends,PC,120.0,winning,Male,18,Unemployed / between jobs,Unknown,France,FRA,Singleplayer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11339,11981,2015-02-19,1,1,1,1,0,0,0,4,League of Legends,PC,0.0,having fun,Male,19,Student at college / university,High school diploma (or equivalent),France,FRA,Multiplayer - online - with real life friends
12779,13535,2015-02-20,0,0,0,0,0,0,0,0,League of Legends,PC,0.0,having fun,Male,20,Student at college / university,High school diploma (or equivalent),Pakistan,PAK,Multiplayer - online - with strangers
58,61,2015-02-17,3,3,1,1,0,1,0,9,Other,PC,0.0,having fun,Male,19,Student at college / university,Unknown,Canada,CAN,Singleplayer
54,56,2015-02-17,2,1,1,3,1,2,0,10,Other,PC,0.0,having fun,Male,19,Student at college / university,High school diploma (or equivalent),USA,USA,Singleplayer
8821,9295,2015-02-19,1,0,0,0,1,0,0,2,League of Legends,PC,0.0,winning,Male,19,Student at college / university,High school diploma (or equivalent),Germany,DEU,"Duo Queue with one good friend, else solo"

## Save cleaned data to csv

In [35]:
gaming_GAD_df.to_csv('../data/gaming_GAD_CLEAN.csv')